// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopApp.ProductsAPI.Data;

#nullable disable

namespace ShopApp.ProductsAPI.ProductsData.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20230624145133_ProductsSeeding")]
    partial class ProductsSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopApp.ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Laptops",
                            Description = "MSI GF63 Thin Gaming Laptop - Intel Core I5 - 8GB RAM - 256GB SSD - 15.6-inch FHD - 4GB GPU - Windows 10 - Black (English Keyboard).",
                            ImageUrl = "/images/products/1.jpg",
                            Name = "MSI GF63 Thin Gaming Laptop",
                            Price = 7800.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Laptops",
                            Description = "DELL G3 15-3500 Gaming Laptop - Intel Core I5-10300H - 8GB RAM - 256GB SSD + 1TB HDD - 15.6-inch FHD - 4GB GTX 1650 GPU - Ubuntu - Black.",
                            ImageUrl = "/images/products/2.jpg",
                            Name = "DELL G3 15-3500 Gaming Laptop",
                            Price = 1240.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Televisions",
                            Description = "Samsung UA43T5300 - 43-inch Full HD Smart TV With Built-In Receiver.",
                            ImageUrl = "/images/products/3.jpg",
                            Name = "Samsung UA43T5300",
                            Price = 650.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Televisions",
                            Description = "LG 43LM6370PVA - 43-inch Full HD Smart TV With Built-in Receiver.",
                            ImageUrl = "/images/products/4.jpg",
                            Name = "LG 43LM6370PVA",
                            Price = 620.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Mobile Phones",
                            Description = "Samsung Galaxy A12 - 6.4-inch 128GB/4GB Dual SIM Mobile Phone - White.",
                            ImageUrl = "/images/products/5.jpg",
                            Name = "Samsung Galaxy A12",
                            Price = 285.0
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Mobile Phones",
                            Description = "Apple iPhone 12 Pro Max Dual SIM with FaceTime - 256GB - Pacific Blue.",
                            ImageUrl = "/images/products/6.jpg",
                            Name = "Apple iPhone 12 Pro Max",
                            Price = 2250.0
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryName = "Mobile Accessories",
                            Description = "OPPO Realme 8 Pro Case, Dual Layer PC Back TPU Bumper Hybrid No-Slip Shockproof Cover For OPPO Realme 8 / Realme 8 Pro 4G.",
                            ImageUrl = "/images/products/7.jpg",
                            Name = "OPPO Realme 8 Pro Case",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryName = "Mobile Accessories",
                            Description = "Galaxy Z Flip3 5G Case, Slim Luxury Electroplate Frame Crystal Clear Back Protective Case Cover For Samsung Galaxy Z Flip 3 5G Purple.",
                            ImageUrl = "/images/products/8.jpg",
                            Name = "Galaxy Z Flip3 5G Case",
                            Price = 25.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
